Specify how to clone submodules
since I always get the error

```
Error: from config: failed to resolve output format "print" from site config
```

when cloning the source code without options.